# Generated by Django 4.2.4 on 2023-09-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_skill_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
