# Generated by Django 4.2.4 on 2023-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_skill',
        ),
        migrations.AddField(
            model_name='job',
            name='required_skill',
            field=models.ManyToManyField(to='marketplace.requiredskill'),
        ),
    ]
