# Generated by Django 4.2.4 on 2023-09-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_required_skill_job_required_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created']},
        ),
    ]
